### ISSUE TITLE
Deprecation Warning on Nuxt.js build due to package.json export

### ISSUE THREAD

**Issue by danperks** [nuxt-modules/icon#140]
When building my Nuxt.js project which uses this package, I get a bunch of deprecation warnings, following this format:

```
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.json" for module request ".//index.json" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules\nitropack\node_modules\_index.js.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.mjs" for module request ".//index.mjs" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules\nitropack\node_modules.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.cjs" for module request ".//index.cjs" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules\nitropack\node_modules.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.js" for module request ".//index.js" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules\nitropack\node_modules.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.json" for module request ".//index.json" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules\nitropack\node_modules.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.mjs" for module request ".//index.mjs" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.cjs" for module request ".//index.cjs" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.js" for module request ".//index.js" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.json" for module request ".//index.json" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules.
(node:2848) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.mjs" for module request ".//index.mjs" matched to "./*" in the "exports" field module resolution of the package at [PROJECT PATH]\node_modules\@iconify\vue\package.json imported from [PROJECT PATH]\node_modules\nuxt\node_modules.
```

This looks to be referring to this line in the Iconify package.json:

https://github.com/iconify/iconify/blob/a8e3b45ecd56e194fd8ef2c3b4eeb6f8c4e68bb1/components/vue/package.json#L27

Have I got a configuration issue, or is this a bug in this library or the Iconify one?
Haven't found any previous reports of this, so this could just be an issue with my project.

I'm on Node v18.17.0, Nuxt v3.8.0 and NuxtIcon v0.6.1
Thanks :)

**Comment by hmingv** [comment]
I have the same problem

Node v20.1
Nuxt V3.10.2
Nuxt-Icon v0.6.8

![image](https://github.com/nuxt-modules/icon/assets/57735185/dd5e1ad3-4c80-4509-8b66-7ef97bbabc0b)

**Comment by cyberalien** [comment]
I've seen this issue in another project after recent update when import path ends with `/`

Maybe there is import somewhere in code that ends with `/`, like tries to import from `@iconify/vue/`? I can't find such code.

**Comment by hmingv** [comment]
Since I couldn't determine the source of the problem, I used the stupidest way to test (deleting files one by one, you need to delete node_modules at the same time and repackage)

When I encountered the .npmrc file, I removed the `shamefully-hoist=true` line and the problem was solved.

I'm not sure if there's any connection, but it does solve my problem for now

**Comment by KarelVendla** [comment]
I also have this in my project

Running
node 20.11.0
nuxt 3.8.2
nuxt-icon 0.6.8

**Comment by ausir0726** [comment]
After my investigation, nuxt starter will write a .npmrc file before September 2023 that includes shamefull-hoist=true. This will cause an issue when running pnpm build. However, this file has been removed as of September 2023. Therefore, if the project was created before, it may still have this file.

No longer see this warning after manually removing the file.

Reference
https://github.com/nuxt/starter/commit/9afba5de755de04965938027a3321a4980b31404

@hmingv Thank you for your helpful response, it saved me from being stuck here like you.

**Comment by lx-elephantxiang** [comment]
@hmingv  I removed the shamefully-hoist=true line and the problem still exists；

**Comment by Kram-V** [comment]
Are you encountering guys right after you  push ur updates in production, the nuxt application will be delayed for a bit of seconds in every page that I navigate? when I already went there on every page, it will become normal navigation again, there's no delay. Is there any connections about this warning or issue of @iconify/vue/ ? btw I deployed my nuxt app using npm run build for ssr in vercel. TIA

**Comment by husayt** [comment]
`shamefully-hoist=true` was causing this for me on windows and pnpm

**Comment by kleinpetr** [comment]
same here, after upgrading Nuxt from `3.9.3` to `3.11.2`

![image](https://github.com/nuxt-modules/icon/assets/17269309/79db2bb1-c72f-485e-b49b-c22039e24534)

**Comment by kleinpetr** [comment]
@Kram-V yes, when I downgrade to `3.9.3` the build has no issue

**Comment by Kram-V** [comment]
@kleinpetr ok tnx

**Comment by kleinpetr** [comment]
@Kram-V oh sorry, it seems that I am getting these warning also with locked `3.9.3` :thinking:  so in my case it's because I removed pnpm.lock after a while, so some deps was cached probably, so cannot specifically...

**Comment by cyberalien** [comment]
> @Kram-V oh sorry, it seems that I am getting these warning also with locked `3.9.3` 🤔 so in my case it's because I removed pnpm.lock after a while, so some deps was cached probably, so cannot specifically...

Try running `pnpm dedupe`

**Comment by Kram-V** [comment]
btw @kleinpetr how can you downgrade ur nuxt app with specific version?

**Comment by Kram-V** [comment]
@kleinpetr I removed the node_modules and package-lock.json and change the version of my nuxt app into ^3.9.3 but when I npm run dev the pop up in the terminal still Nuxt 3.11.2 why is that?

**Comment by cyberalien** [comment]
Remove `^` from version number

**Comment by Kram-V** [comment]
@cyberalien ok sir I will try

**Comment by eeg1412** [comment]
Issue similar to [Iconify/iconify#283](https://github.com/iconify/iconify/issues/283) exists.

Also, for Nuxt I recommend using `iconify-icon` package, not `@iconify/vue`. See [Iconify Icon SSR](https://iconify.design/docs/iconify-icon/#ssr) for details.

**Comment by DbPtZn** [comment]
Me too.But it doesn't seem to affect the program's operation

**Comment by antfu** [comment]
Can anyone send a minimal reproduction so I can have a deeper look?

**Comment by ojvribeiro** [comment]
@antfu here is the repro: https://github.com/ojvribeiro/nuxt-repro-deprecation-warning

It is a fresh Nuxt project and Nuxt Icon is the only module installed. When I run the build command the Deprecation Warning message is spammed:

![image](https://github.com/user-attachments/assets/9079834d-b76b-477f-9964-0f812e5dbf4c)

**Comment by cyberalien** [comment]
> @antfu here is the repro: https://github.com/ojvribeiro/nuxt-repro-deprecation-warning

That reproduction doesn't show any warnings when running build command on MacOS or Linux.

Looking at this screenshot and previous screenshots, all reports use `\` in path, so looks like a Windows only issue.

**Comment by evermake** [comment]
> Looking at this screenshot and previous screenshots, all reports use `\` in path, so looks like a Windows only issue.

Actually, no, I have the similar issue on MacOS:

```
...
(node:9206) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.cjs" for module request ".//index.cjs" matched to "./*" in the "exports" field module resolution of the package at /Users/evermake/Code/project/node_modules/.pnpm/node_modules/@iconify/utils/package.json imported from /Users/evermake/Code/project/node_modules/.pnpm/nitropack@2.9.7_encoding@0.1.13_magicast@0.3.4/.
(node:9206) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.js" for module request ".//index.js" matched to "./*" in the "exports" field module resolution of the package at /Users/evermake/Code/project/node_modules/.pnpm/node_modules/@iconify/utils/package.json imported from /Users/evermake/Code/project/node_modules/.pnpm/nitropack@2.9.7_encoding@0.1.13_magicast@0.3.4/.
(node:9206) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.json" for module request ".//index.json" matched to "./*" in the "exports" field module resolution of the package at /Users/evermake/Code/project/node_modules/.pnpm/node_modules/@iconify/utils/package.json imported from /Users/evermake/Code/project/node_modules/.pnpm/nitropack@2.9.7_encoding@0.1.13_magicast@0.3.4/.
... (and more similar issues below...)
```

```
npx envinfo --system --binaries --browsers

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 141.55 MB / 16.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.13.1 - ~/Library/Caches/fnm_multishells/8351_1722461424558/bin/node
    npm: 10.5.2 - ~/Library/Caches/fnm_multishells/8351_1722461424558/bin/npm
    pnpm: 9.6.0 - ~/Library/Caches/fnm_multishells/8351_1722461424558/bin/pnpm
    bun: 1.1.20 - ~/.bun/bin/bun
  Browsers:
    Safari: 17.5
```

**Comment by cyberalien** [comment]
> Actually, no, I have the similar issue on MacOS:

Can you post a reproduction?

**Comment by nwrman** [comment]
Same issue here

Running
node 20.16.0
nuxt 3.12.3
@nuxt/icon 1.4.3

**Comment by cyberalien** [comment]
> Same issue here
> 
> Running node 20.16.0 nuxt 3.12.3 @nuxt/icon 1.4.3

On Windows?

**Comment by nwrman** [comment]
Yes, sorry, on windows

**Comment by shadKamel** [comment]
i have same issue, 
Running
node 20.16.0
nuxt 3.12.3
@nuxt/icon 1.4.3

**Comment by evermake** [comment]
> > Actually, no, I have the similar issue on MacOS:
> 
> Can you post a reproduction?

Sorry, but not for now. Had this in issue in a private project with many dependencies. Probably, will share a reproduction if the problem will remain and I'll have more time to investigate.

**Comment by thyngster** [comment]
I was "trying" to find a fix for this. My current test env,. is latest nuxt + latest vueuse . 
```
  "dependencies": {
    "@vueuse/core": "^11.0.3",
    "nuxt": "^3.13.0",
    "vue": "latest"
  },
```
I'm seeing the issue also happening only starting from Nitro 2.6.0 ( ie downgrading to 2.5.2 will prevent the error to show up ) , not the best option since for example there's not ESM WASM support. 

So not sure if this is totally related to Nuxt part or Nitro at all.  
```
Deprecation Trace: ( node --trace-deprecation node_modules/nuxt/bin/nuxt.mjs build )

Building Nitro Server (preset: node-server)                                                                                                                                    nitro 3:23:52 AM
(node:40556) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at C:\Users\david\Documents\my-nuxt-app\node_modules\@vueuse\core\package.json imported from C:\Users\david\Documents\my-nuxt-app\node_modules. Mapping specifiers ending in "/" is no longer supported.
    at emitTrailingSlashPatternDeprecation (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1526:13)
    at packageExportsResolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1602:9)
    at packageResolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1859:14)
    at moduleResolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1954:18)
    at _tryModuleResolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2023:12)
    at _resolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2078:16)
    at resolveSync (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2111:10)
    at resolvePathSync (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2121:24)
    at resolvePath (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2125:28)
    at _resolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/nitropack/dist/shared/nitro.82977d3c.mjs:461:22)
(node:40556) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.mjs" for module request ".//index.mjs" matched to "./*" in the "exports" field module resolution of the package at C:\Users\david\Documents\my-nuxt-app\node_modules\@vueuse\core\package.json imported from C:\Users\david\Documents\my-nuxt-app\node_modules.
    at emitInvalidSegmentDeprecation (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:917:13)
    at resolvePackageTargetString (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1301:9)
    at resolvePackageTarget (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1363:12)
    at packageExportsResolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1629:27)
    at packageResolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1859:14)
    at moduleResolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:1954:18)
    at _tryModuleResolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2023:12)
    at _resolve (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2084:20)
    at resolveSync (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2111:10)
    at resolvePathSync (file:///C:/Users/david/Documents/my-nuxt-app/node_modules/mlly/dist/index.mjs:2121:24)
✔ Nitro server built                                                                                                                                                             nitro 3:23:54 AM
```

Also not only DEP0166 is triggered also the DEP0155. may be it related at some poting to https://github.com/unjs/nitro/issues/2523 ?

This mayu not be

**Comment by WilliamFalci** [comment]
Hello guys,

by all my test:

- OS: Window
- Node: 18.x - 20.x - 22.x

I confirm the issue is only on Windows, after windows I tried Ubuntu and everything worked without changes

**Comment by dencs08** [comment]
Running `pnpm build` or `npm run build` throws 

`Use of deprecated trailing slash pattern mapping...` or `Use of deprecated doulbe slash resolving...`

 It happens only on windows while on macos it builds perfectly fine.

**Comment by itpropro** [comment]
Just in case anyone comes across this and wants to suppress the errors, you can prepend you script in your package.json with this under **Windows** until the bug is fixed:

`set NODE_OPTIONS=--disable-warning=DEP0155 --disable-warning=DEP0166 && `

```
  "scripts": {
    "build": "set NODE_OPTIONS=--disable-warning=DEP0155 --disable-warning=DEP0166 && nitro build",
```

cross-env would be the better choice for cross platform, but this is just temporary until the cause was found.

**Comment by tinegaCollins** [comment]
was this issue fixed?

**Comment by clopezpro** [comment]
I have this error in Windows, on the Linux production server it works well
![Image](https://github.com/user-attachments/assets/73a5481a-9853-4e7a-887b-d1e22e4a814a)

**Comment by hdy1023** [comment]
same problem on windows.
`(node:39932) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at D:\project\ai-paient\front-web\node_modules\.pnpm\@nuxt+icon@1.11.0_magicast@0.3.5_vite@6.2.2_@types+node@22.10.0_jiti@2.4.2_less@4.2.2_lightni_xiyjlmoe3pd5so5vcpao6chan4\node_modules\@iconify\utils\package.json imported from D:\project\ai-paient\front-web\node_modules\.pnpm\@nuxt+icon@1.11.0_magicast@0.3.5_vite@6.2.2_@types+node@22.10.0_jiti@2.4.2_less@4.2.2_lightni_xiyjlmoe3pd5so5vcpao6chan4\node_modules\@nuxt\icon\dist\runtime\server\api.js. Mapping specifiers ending in "/" is no longer supported.       
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:39932) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at D:\project\ai-paient\front-web\node_modules\@iconify\utils\package.json imported from D:\project\ai-paient\front-web\node_modules\. Mapping specifiers ending in "/" is no longer supported.
(node:39932) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at D:\project\ai-paient\front-web\node_modules\@iconify\vue\package.json imported from D:\project\ai-paient\front-web\.nuxt\dist\server\node_modules\.pnpm\_nuxt_icon_1.11.0_magicast_0.3.5_vite_6.2.2__types_node_22.10.0_jiti_2.4.2_less_4.2.2_lightni_xiyjlmoe3pd5so5vcpao6chan4\node_modules\_nuxt\icon\dist\runtime\plugin.mjs. Mapping specifiers ending in "/" is no longer supported.
(node:39932) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at D:\project\ai-paient\front-web\node_modules\.pnpm\@nuxt+icon@1.11.0_magicast@0.3.5_vite@6.2.2_@types+node@22.10.0_jiti@2.4.2_less@4.2.2_lightni_xiyjlmoe3pd5so5vcpao6chan4\node_modules\@iconify\vue\package.json imported from D:\project\ai-paient\front-web\node_modules\.pnpm\@nuxt+icon@1.11.0_magicast@0.3.5_vite@6.2.2_@types+node@22.10.0_jiti@2.4.2_less@4.2.2_lightni_xiyjlmoe3pd5so5vcpao6chan4\node_modules\@nuxt\icon\node_modules\. Mapping specifiers ending in "/" is no longer supported.
(node:39932) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at D:\project\ai-paient\front-web\node_modules\.pnpm\@nuxt+ui@3.0.0_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_embla-carousel@8.5.2_ioredis_e2fdewizxl6nkbbrlelx27wu6u\node_modules\@iconify\vue\package.json imported from D:\project\ai-paient\front-web\node_modules\.pnpm\@nuxt+ui@3.0.0_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_embla-carousel@8.5.2_ioredis_e2fdewizxl6nkbbrlelx27wu6u\node_modules\@nuxt\ui\node_modules\. Mapping specifiers ending in "/" is no longer supported.`

![Image](https://github.com/user-attachments/assets/b50dec39-7504-40a6-af7f-652dab262f58)

**Comment by cyberalien** [comment]
In version 5 of Iconify icon component removed wildcard import.

While this issue affects only Windows, so it is a Node bug, it can be annoying, so it is worth fixing. I don't think wildcard import is even used, so this shouldn't break anything. In case it does break stuff, new version is released as beta using `next` tag.

You can install it as `@iconify/vue@next`. I think it should work without any issues with Nuxt Icon.

**Comment by cyberalien** [comment]
> Same here after updating to Nuxt 3.16.2. [@cyberalien](https://github.com/cyberalien) what do you mean "install it as @iconify/vue@next"? 🤔

`npm install @iconify/vue@next` (or pnpm/yarn equivalent)

**Comment by TimGuendel** [comment]
Yeah, that's what I had tried - it led to this.

> Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@iconify+vue@5.0.0-beta.2_vue@3.5.13_typescript@5.6.3_/node_modules/@iconify/vue/dist/iconify.mjs?v=19fb84fc' does not provide an export named 'disableCache' (at plugin.js?v=19fb84fc:1:32)

Is this an indirect dependency problem, or is it related to those entries in my package.json? 🤔
```
        "@iconify-json/fa-solid": "^1.2.1",
        "@iconify-json/heroicons": "^1.2.2",
        "@iconify-json/mdi": "^1.2.3",
        "@iconify-json/solar": "^1.2.2",
```

**Comment by TimGuendel** [comment]
Yeah, that's what I had tried - it led to this.

> Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@iconify+vue@5.0.0-beta.2_vue@3.5.13_typescript@5.6.3_/node_modules/@iconify/vue/dist/iconify.mjs?v=19fb84fc' does not provide an export named 'disableCache' (at plugin.js?v=19fb84fc:1:32)

Is this an indirect dependency problem, or is it related to those entries in my package.json? 🤔
```
        "@iconify-json/fa-solid": "^1.2.1",
        "@iconify-json/heroicons": "^1.2.2",
        "@iconify-json/mdi": "^1.2.3",
        "@iconify-json/solar": "^1.2.2",
```

**Comment by cyberalien** [comment]
> Yeah, that's what I had tried - it led to this.
> 
> > Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/[@iconify](https://github.com/iconify)+vue@5.0.0-beta.2_vue@3.5.13_typescript@5.6.3_/node_modules/@iconify/vue/dist/iconify.mjs?v=19fb84fc' does not provide an export named 'disableCache' (at plugin.js?v=19fb84fc:1:32)
> 
> Is this an indirect dependency problem, or is it related to those entries in my package.json? 🤔

That needs to be changed in Nuxt Icon. It was a function in old version of Iconify Icon component, later deprecated but export kept for backwards compatibility, in new version removed completely.

I'll make a PR to remove its usage from Nuxt Icon.

So that means for now workaround won't work.

**Comment by cyberalien** [comment]
> Yeah, that's what I had tried - it led to this.
> 
> > Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/[@iconify](https://github.com/iconify)+vue@5.0.0-beta.2_vue@3.5.13_typescript@5.6.3_/node_modules/@iconify/vue/dist/iconify.mjs?v=19fb84fc' does not provide an export named 'disableCache' (at plugin.js?v=19fb84fc:1:32)
> 
> Is this an indirect dependency problem, or is it related to those entries in my package.json? 🤔

You need to update Nuxt Icon. That function was removed about a month ago

**Comment by TimGuendel** [comment]
This did not solve the problem - I guess I'll wait 👀

**Comment by cyberalien** [comment]
You can create a small reproduction of bug and submit it to Node.js, so they would fix invalid deprecation warning.

I can't do that because it happens only on Windows and I don't use Windows.

**Comment by taducquang** [comment]
even nuxt starter boilerplate - https://github.com/nuxt/starter/tree/ui will immediately result in those "Use of deprecated trailing slash pattern mapping "./" errors when using pnpm build.

**Comment by Hibrix-net** [comment]
> Just in case anyone comes across this and wants to suppress the errors, you can prepend you script in your package.json with this under **Windows** until the bug is fixed:
> 
> `set NODE_OPTIONS=--disable-warning=DEP0155 --disable-warning=DEP0166 && `
> 
> ```
>   "scripts": {
>     "build": "set NODE_OPTIONS=--disable-warning=DEP0155 --disable-warning=DEP0166 && nitro build",
> ```
> 
> cross-env would be the better choice for cross platform, but this is just temporary until the cause was found.

Hi, I’ve tried this, but the build still gets stuck. Could anyone help with building on Windows using @nuxt/ui? At this point, it feels nearly impossible to get it working. Any workaround?

**Comment by Hibrix-net** [comment]
> > Its just a warning, it doesn't break anything.  You can build your project and ignore this warning.
> 
> The build process is stopped with this warning. Other packages ([@iconify](https://github.com/iconify),[@VUE](https://github.com/VUE),[@vueuse](https://github.com/vueuse)) are mentioned too.

It is not, at least in my case. The build got stucked at that point right after those warnings. I'm trying to build the Nuxt started boilerplate as @taducquang described above.

**Comment by cyberalien** [comment]
> > Its just a warning, it doesn't break anything.  You can build your project and ignore this warning.
> 
> The build process is stopped with this warning. Other packages (iconify,vue,vueuse) are mentioned too.

Something else is doing that. Deprecation warning (even though it is a false positive) is just a warning, nothing else.

Be aware that many developers don't have access to Windows and/or don't care about Windows support, so there can be a number of issues. Environment is a mess, it is hard to debug and account for potential Windows problems. For better Windows development there is WSL, so do try to switch to it.

**Comment by Hibrix-net** [comment]
> > > Its just a warning, it doesn't break anything.  You can build your project and ignore this warning.
> > 
> > 
> > The build process is stopped with this warning. Other packages (iconify,vue,vueuse) are mentioned too.
> 
> Something else is doing that. Deprecation warning (even though it is a false positive) is just a warning, nothing else.
> 
> Be aware that many developers don't have access to Windows and/or don't care about Windows support, so there can be a number of issues. Environment is a mess, it is hard to debug and account for potential Windows problems. For better Windows development there is WSL, so do try to switch to it.

I only know that I installed the Nuxt starter as-is and got stuck at build time. I’m not sure I can fully agree with “not caring about Windows support” for something like Nuxt. I tried WSL years ago and it was painfully slow, but maybe it’s worth giving it another shot now. Thanks.
